# Simple toy configuration

global:
  name: toy
  n_meas: 2
  n_syst: 2
  corr_dir: tutorials/toy/input file/correlations/

data:
  measurements:
    - label: m1
      central: 1.0
      stat_error: 0.1
    - label: m2
      central: 1.2
      stat_error: 0.1

syst:
  - name: sys_dep
    shifts: [0.1, -0.2]
    type:
      dependent: dep_corr.txt
    epsilon: 0.1
  - name: sys_ind
    shifts: [0.05, 0.05]
    type: independent
    epsilon: 0.1
